name: cs229-fp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyterlab
  - ffmpeg 
  - jpeg
  - pip
  - pip:
      - av
      - opencv-python  
      - tqdm           # For progress bars during training